export const SET_SHOW_ADD_PRODUCT_MODAL = "SET_SHOW_ADD_PRODUCT_MODAL";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const SORT_BY_ALPHABET = "SORT_BY_ALPHABET";
export const SORT_BY_COUNT = "SORT_BY_COUNT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
